PUT http://localhost:3001/api/blogs/5fb2bd50184e8f363c1c92cf
Content-Type: application/json

{
    "title": "Кулинарный блог Оли",
    "author": "Оля",
    "url": "//https/olayfoods/blog",
    "likes": 15,
    "id": "5fb2bd50184e8f363c1c92cf"
}